version: '3'
services:
  teisis:
    build: .
    container_name: TeISIS
    restart: always
    volumes:
      - ./waves:/app/waves
      - ./trained:/app/trained
      - ./config:/app/config      
    ports:
      - "5000:5000"

